version: '3.9'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
